name: Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Backend to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.BE_HOST }} "
          if [ ! -d '~/UTSCODE/.git' ]; then
            git clone https://github.com/brmntiosa/UTSCODE.git ~/UTSCODE
          else
            cd ~/UTSCODE
            git pull origin main
          fi
          cd ~/UTSCODE
          pm2 restart app || node app.js &
        "

    - name: Deploy Frontend to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.FE_HOST }} "
          if [ ! -d '/var/www/html/.git' ]; then
            sudo rm -rf /var/www/html/*
            cd /var/www/html
            sudo git clone https://github.com/brmntiosa/UTSCODE.git .
            sudo rm -rf node_modules package-lock.json package.json README.md app.js
          else
            cd /var/www/html
            sudo git pull origin main
          fi
          sudo systemctl restart httpd
        "
