name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Backend EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.BE_HOST }} "
          cd UTSCODE && 
          git pull origin main && 
          pm2 restart app || node app.js &
        "

    # - name: Deploy to Frontend EC2
    #   run: |
    #     ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.FE_HOST }} "
    #       cd /var/www/html && 
    #       sudo git pull origin main &&
    #       sudo systemctl restart httpd
    #     "
